name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login
        uses: ./
        with:
          registry: test.ghcr.io
          username: test
          password: testing
      - name: dump
        shell: bash
        run: cat "${HOME}/.docker/config.json"
      -
        name: Dump after
        uses: webiny/action-post-run@2.0.1
        with:
          run: cat "${HOME}/.docker/config.json"
